/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import ru.doslano.sdk.ApiCallback;
import ru.doslano.sdk.ApiClient;
import ru.doslano.sdk.ApiException;
import ru.doslano.sdk.ApiResponse;
import ru.doslano.sdk.Configuration;
import ru.doslano.sdk.Pair;
import ru.doslano.sdk.ProgressRequestBody;
import ru.doslano.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.WebhookEvent;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for onLetterStatusChanged
     * @param webhookEvent  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Принято (любой 2xx останавливает ретраи). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onLetterStatusChangedCall(WebhookEvent webhookEvent, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = webhookEvent;

        // create path and map variables
        String localVarPath = "/letterStatusChanged";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onLetterStatusChangedValidateBeforeCall(WebhookEvent webhookEvent, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'webhookEvent' is set
        if (webhookEvent == null) {
            throw new ApiException("Missing the required parameter 'webhookEvent' when calling onLetterStatusChanged(Async)");
        }

        return onLetterStatusChangedCall(webhookEvent, _callback);

    }

    /**
     * Колбек на финальный статус
     * Если при отправке письма указан &#x60;callback_url&#x60;, мы шлём на него POST при достижении финального статуса — по каждому получателю (&#x60;recipient.sent&#x60; / &#x60;recipient.failed&#x60;) и агрегатно по письму (&#x60;letter.sent&#x60; / &#x60;letter.partial_failure&#x60; / &#x60;letter.failed&#x60; / &#x60;letter.cancelled&#x60;).  Отдельный случай &#x60;letter.cancelled&#x60; — когда адрес/ФИО не прошли проверку Почты России **уже после** ответа &#x60;201&#x60; (поздний preflight: проверка не успела завершиться в окне синхронного ответа). Письмо отменяется автоматически, в &#x60;data.error&#x60; — перечень полей с ошибками; исправьте данные и создайте письмо заново. Если же ошибка адреса выявлена **сразу** при создании — вы получаете её синхронно (HTTP 422 &#x60;address_validation_failed&#x60;), и колбек по такому письму НЕ шлётся. То есть на одно письмо приходит ровно один сигнал об адресной ошибке: либо синхронный 422, либо асинхронный &#x60;letter.cancelled&#x60;.  **Подпись.** Заголовок &#x60;X-Doslano-Signature: t&#x3D;&lt;unix&gt;,v1&#x3D;&lt;hex&gt;&#x60; — где &#x60;v1 &#x3D; HMAC_SHA256(secret, \&quot;&lt;t&gt;.\&quot; + raw_body)&#x60;, &#x60;secret&#x60; — секрет аккаунта из ЛК (раздел «API»). Проверьте подпись и свежесть &#x60;t&#x60; (±5 мин).  **Доставка.** At-least-once: ждём ответ &#x60;2xx&#x60;; иначе ретраим по нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем как недоставленный (видно в ЛК, можно переотправить). Дедуп — по &#x60;id&#x60; события. Порядок не гарантируется — сверяйтесь со &#x60;status&#x60; в теле. 
     * @param webhookEvent  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Принято (любой 2xx останавливает ретраи). </td><td>  -  </td></tr>
     </table>
     */
    public void onLetterStatusChanged(WebhookEvent webhookEvent) throws ApiException {
        onLetterStatusChangedWithHttpInfo(webhookEvent);
    }

    /**
     * Колбек на финальный статус
     * Если при отправке письма указан &#x60;callback_url&#x60;, мы шлём на него POST при достижении финального статуса — по каждому получателю (&#x60;recipient.sent&#x60; / &#x60;recipient.failed&#x60;) и агрегатно по письму (&#x60;letter.sent&#x60; / &#x60;letter.partial_failure&#x60; / &#x60;letter.failed&#x60; / &#x60;letter.cancelled&#x60;).  Отдельный случай &#x60;letter.cancelled&#x60; — когда адрес/ФИО не прошли проверку Почты России **уже после** ответа &#x60;201&#x60; (поздний preflight: проверка не успела завершиться в окне синхронного ответа). Письмо отменяется автоматически, в &#x60;data.error&#x60; — перечень полей с ошибками; исправьте данные и создайте письмо заново. Если же ошибка адреса выявлена **сразу** при создании — вы получаете её синхронно (HTTP 422 &#x60;address_validation_failed&#x60;), и колбек по такому письму НЕ шлётся. То есть на одно письмо приходит ровно один сигнал об адресной ошибке: либо синхронный 422, либо асинхронный &#x60;letter.cancelled&#x60;.  **Подпись.** Заголовок &#x60;X-Doslano-Signature: t&#x3D;&lt;unix&gt;,v1&#x3D;&lt;hex&gt;&#x60; — где &#x60;v1 &#x3D; HMAC_SHA256(secret, \&quot;&lt;t&gt;.\&quot; + raw_body)&#x60;, &#x60;secret&#x60; — секрет аккаунта из ЛК (раздел «API»). Проверьте подпись и свежесть &#x60;t&#x60; (±5 мин).  **Доставка.** At-least-once: ждём ответ &#x60;2xx&#x60;; иначе ретраим по нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем как недоставленный (видно в ЛК, можно переотправить). Дедуп — по &#x60;id&#x60; события. Порядок не гарантируется — сверяйтесь со &#x60;status&#x60; в теле. 
     * @param webhookEvent  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Принято (любой 2xx останавливает ретраи). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> onLetterStatusChangedWithHttpInfo(WebhookEvent webhookEvent) throws ApiException {
        okhttp3.Call localVarCall = onLetterStatusChangedValidateBeforeCall(webhookEvent, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Колбек на финальный статус (asynchronously)
     * Если при отправке письма указан &#x60;callback_url&#x60;, мы шлём на него POST при достижении финального статуса — по каждому получателю (&#x60;recipient.sent&#x60; / &#x60;recipient.failed&#x60;) и агрегатно по письму (&#x60;letter.sent&#x60; / &#x60;letter.partial_failure&#x60; / &#x60;letter.failed&#x60; / &#x60;letter.cancelled&#x60;).  Отдельный случай &#x60;letter.cancelled&#x60; — когда адрес/ФИО не прошли проверку Почты России **уже после** ответа &#x60;201&#x60; (поздний preflight: проверка не успела завершиться в окне синхронного ответа). Письмо отменяется автоматически, в &#x60;data.error&#x60; — перечень полей с ошибками; исправьте данные и создайте письмо заново. Если же ошибка адреса выявлена **сразу** при создании — вы получаете её синхронно (HTTP 422 &#x60;address_validation_failed&#x60;), и колбек по такому письму НЕ шлётся. То есть на одно письмо приходит ровно один сигнал об адресной ошибке: либо синхронный 422, либо асинхронный &#x60;letter.cancelled&#x60;.  **Подпись.** Заголовок &#x60;X-Doslano-Signature: t&#x3D;&lt;unix&gt;,v1&#x3D;&lt;hex&gt;&#x60; — где &#x60;v1 &#x3D; HMAC_SHA256(secret, \&quot;&lt;t&gt;.\&quot; + raw_body)&#x60;, &#x60;secret&#x60; — секрет аккаунта из ЛК (раздел «API»). Проверьте подпись и свежесть &#x60;t&#x60; (±5 мин).  **Доставка.** At-least-once: ждём ответ &#x60;2xx&#x60;; иначе ретраим по нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем как недоставленный (видно в ЛК, можно переотправить). Дедуп — по &#x60;id&#x60; события. Порядок не гарантируется — сверяйтесь со &#x60;status&#x60; в теле. 
     * @param webhookEvent  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Принято (любой 2xx останавливает ретраи). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onLetterStatusChangedAsync(WebhookEvent webhookEvent, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = onLetterStatusChangedValidateBeforeCall(webhookEvent, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
