/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import ru.doslano.sdk.ApiCallback;
import ru.doslano.sdk.ApiClient;
import ru.doslano.sdk.ApiException;
import ru.doslano.sdk.ApiResponse;
import ru.doslano.sdk.Configuration;
import ru.doslano.sdk.Pair;
import ru.doslano.sdk.ProgressRequestBody;
import ru.doslano.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.CreateLetterRequest;
import org.openapitools.client.model.DryRunResult;
import org.openapitools.client.model.Letter;
import org.openapitools.client.model.LetterStatus;
import org.openapitools.client.model.ListLetters200Response;
import java.time.OffsetDateTime;
import org.openapitools.client.model.Problem;
import org.openapitools.client.model.TrackingInfo;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LettersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LettersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LettersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createLetter
     * @param createLetterRequest  (required)
     * @param idempotencyKey Ключ идемпотентности. Повтор с тем же ключом в течение TTL вернёт исходный результат, не создавая письмо повторно. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Письмо принято. Тело — состояние письма (включая цену и результат промокода). </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Пробный прогон (&#x60;dry_run: true&#x60;) успешен: запрос валиден, показан расчёт. Письмо не создано, средства не списаны. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Некорректный запрос. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Недостаточно средств на балансе (при &#x60;on_insufficient_funds&#x3D;reject&#x60;). </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Ошибка валидации данных письма (адрес, файл, получатели и т.п.). В частности &#x60;code: address_validation_failed&#x60; — адрес/ФИО не прошли preflight-проверку Почты России: письмо отменено, в &#x60;detail&#x60; перечислены стороны и поля; исправьте данные и создайте письмо заново. Коды &#x60;recipient_address_unresolved&#x60; и &#x60;recipient_resolve_requires_inn&#x60; относятся к опции &#x60;resolve_address_by_inn&#x60; (см. RecipientInput). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createLetterCall(CreateLetterRequest createLetterRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createLetterRequest;

        // create path and map variables
        String localVarPath = "/v1/letters";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createLetterValidateBeforeCall(CreateLetterRequest createLetterRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createLetterRequest' is set
        if (createLetterRequest == null) {
            throw new ApiException("Missing the required parameter 'createLetterRequest' when calling createLetter(Async)");
        }

        return createLetterCall(createLetterRequest, idempotencyKey, _callback);

    }

    /**
     * Отправить письмо
     * Создаёт и (по умолчанию) сразу оплачивает с баланса одно заказное письмо одним запросом. Опись формируется автоматически на нашей стороне.  Требуется scope &#x60;letters:write&#x60;. 
     * @param createLetterRequest  (required)
     * @param idempotencyKey Ключ идемпотентности. Повтор с тем же ключом в течение TTL вернёт исходный результат, не создавая письмо повторно. (optional)
     * @return DryRunResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Письмо принято. Тело — состояние письма (включая цену и результат промокода). </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Пробный прогон (&#x60;dry_run: true&#x60;) успешен: запрос валиден, показан расчёт. Письмо не создано, средства не списаны. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Некорректный запрос. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Недостаточно средств на балансе (при &#x60;on_insufficient_funds&#x3D;reject&#x60;). </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Ошибка валидации данных письма (адрес, файл, получатели и т.п.). В частности &#x60;code: address_validation_failed&#x60; — адрес/ФИО не прошли preflight-проверку Почты России: письмо отменено, в &#x60;detail&#x60; перечислены стороны и поля; исправьте данные и создайте письмо заново. Коды &#x60;recipient_address_unresolved&#x60; и &#x60;recipient_resolve_requires_inn&#x60; относятся к опции &#x60;resolve_address_by_inn&#x60; (см. RecipientInput). </td><td>  -  </td></tr>
     </table>
     */
    public DryRunResult createLetter(CreateLetterRequest createLetterRequest, String idempotencyKey) throws ApiException {
        ApiResponse<DryRunResult> localVarResp = createLetterWithHttpInfo(createLetterRequest, idempotencyKey);
        return localVarResp.getData();
    }

    /**
     * Отправить письмо
     * Создаёт и (по умолчанию) сразу оплачивает с баланса одно заказное письмо одним запросом. Опись формируется автоматически на нашей стороне.  Требуется scope &#x60;letters:write&#x60;. 
     * @param createLetterRequest  (required)
     * @param idempotencyKey Ключ идемпотентности. Повтор с тем же ключом в течение TTL вернёт исходный результат, не создавая письмо повторно. (optional)
     * @return ApiResponse&lt;DryRunResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Письмо принято. Тело — состояние письма (включая цену и результат промокода). </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Пробный прогон (&#x60;dry_run: true&#x60;) успешен: запрос валиден, показан расчёт. Письмо не создано, средства не списаны. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Некорректный запрос. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Недостаточно средств на балансе (при &#x60;on_insufficient_funds&#x3D;reject&#x60;). </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Ошибка валидации данных письма (адрес, файл, получатели и т.п.). В частности &#x60;code: address_validation_failed&#x60; — адрес/ФИО не прошли preflight-проверку Почты России: письмо отменено, в &#x60;detail&#x60; перечислены стороны и поля; исправьте данные и создайте письмо заново. Коды &#x60;recipient_address_unresolved&#x60; и &#x60;recipient_resolve_requires_inn&#x60; относятся к опции &#x60;resolve_address_by_inn&#x60; (см. RecipientInput). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DryRunResult> createLetterWithHttpInfo(CreateLetterRequest createLetterRequest, String idempotencyKey) throws ApiException {
        okhttp3.Call localVarCall = createLetterValidateBeforeCall(createLetterRequest, idempotencyKey, null);
        Type localVarReturnType = new TypeToken<DryRunResult>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Отправить письмо (asynchronously)
     * Создаёт и (по умолчанию) сразу оплачивает с баланса одно заказное письмо одним запросом. Опись формируется автоматически на нашей стороне.  Требуется scope &#x60;letters:write&#x60;. 
     * @param createLetterRequest  (required)
     * @param idempotencyKey Ключ идемпотентности. Повтор с тем же ключом в течение TTL вернёт исходный результат, не создавая письмо повторно. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Письмо принято. Тело — состояние письма (включая цену и результат промокода). </td><td>  -  </td></tr>
        <tr><td> 200 </td><td> Пробный прогон (&#x60;dry_run: true&#x60;) успешен: запрос валиден, показан расчёт. Письмо не создано, средства не списаны. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Некорректный запрос. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Недостаточно средств на балансе (при &#x60;on_insufficient_funds&#x3D;reject&#x60;). </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Ошибка валидации данных письма (адрес, файл, получатели и т.п.). В частности &#x60;code: address_validation_failed&#x60; — адрес/ФИО не прошли preflight-проверку Почты России: письмо отменено, в &#x60;detail&#x60; перечислены стороны и поля; исправьте данные и создайте письмо заново. Коды &#x60;recipient_address_unresolved&#x60; и &#x60;recipient_resolve_requires_inn&#x60; относятся к опции &#x60;resolve_address_by_inn&#x60; (см. RecipientInput). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createLetterAsync(CreateLetterRequest createLetterRequest, String idempotencyKey, final ApiCallback<DryRunResult> _callback) throws ApiException {

        okhttp3.Call localVarCall = createLetterValidateBeforeCall(createLetterRequest, idempotencyKey, _callback);
        Type localVarReturnType = new TypeToken<DryRunResult>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getLetter
     * @param id Идентификатор письма. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Состояние письма. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ресурс не найден (или не принадлежит аккаунту). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLetterCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/letters/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLetterValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getLetter(Async)");
        }

        return getLetterCall(id, _callback);

    }

    /**
     * Статус письма
     * Полное состояние письма с разбивкой по получателям и трек-номерами. Требуется scope &#x60;letters:read&#x60;.
     * @param id Идентификатор письма. (required)
     * @return Letter
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Состояние письма. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ресурс не найден (или не принадлежит аккаунту). </td><td>  -  </td></tr>
     </table>
     */
    public Letter getLetter(String id) throws ApiException {
        ApiResponse<Letter> localVarResp = getLetterWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Статус письма
     * Полное состояние письма с разбивкой по получателям и трек-номерами. Требуется scope &#x60;letters:read&#x60;.
     * @param id Идентификатор письма. (required)
     * @return ApiResponse&lt;Letter&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Состояние письма. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ресурс не найден (или не принадлежит аккаунту). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Letter> getLetterWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getLetterValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Letter>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Статус письма (asynchronously)
     * Полное состояние письма с разбивкой по получателям и трек-номерами. Требуется scope &#x60;letters:read&#x60;.
     * @param id Идентификатор письма. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Состояние письма. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ресурс не найден (или не принадлежит аккаунту). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLetterAsync(String id, final ApiCallback<Letter> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLetterValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Letter>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRecipientTracking
     * @param id Идентификатор письма. (required)
     * @param recipientId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> События трекинга. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ресурс не найден (или не принадлежит аккаунту). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRecipientTrackingCall(String id, String recipientId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/letters/{id}/recipients/{recipient_id}/tracking"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()))
            .replace("{" + "recipient_id" + "}", localVarApiClient.escapeString(recipientId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRecipientTrackingValidateBeforeCall(String id, String recipientId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getRecipientTracking(Async)");
        }

        // verify the required parameter 'recipientId' is set
        if (recipientId == null) {
            throw new ApiException("Missing the required parameter 'recipientId' when calling getRecipientTracking(Async)");
        }

        return getRecipientTrackingCall(id, recipientId, _callback);

    }

    /**
     * Трек-события получателя
     * События трекинга Почты России по конкретному получателю (если трек-номер присвоен). Требуется scope &#x60;letters:read&#x60;.
     * @param id Идентификатор письма. (required)
     * @param recipientId  (required)
     * @return TrackingInfo
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> События трекинга. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ресурс не найден (или не принадлежит аккаунту). </td><td>  -  </td></tr>
     </table>
     */
    public TrackingInfo getRecipientTracking(String id, String recipientId) throws ApiException {
        ApiResponse<TrackingInfo> localVarResp = getRecipientTrackingWithHttpInfo(id, recipientId);
        return localVarResp.getData();
    }

    /**
     * Трек-события получателя
     * События трекинга Почты России по конкретному получателю (если трек-номер присвоен). Требуется scope &#x60;letters:read&#x60;.
     * @param id Идентификатор письма. (required)
     * @param recipientId  (required)
     * @return ApiResponse&lt;TrackingInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> События трекинга. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ресурс не найден (или не принадлежит аккаунту). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TrackingInfo> getRecipientTrackingWithHttpInfo(String id, String recipientId) throws ApiException {
        okhttp3.Call localVarCall = getRecipientTrackingValidateBeforeCall(id, recipientId, null);
        Type localVarReturnType = new TypeToken<TrackingInfo>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Трек-события получателя (asynchronously)
     * События трекинга Почты России по конкретному получателю (если трек-номер присвоен). Требуется scope &#x60;letters:read&#x60;.
     * @param id Идентификатор письма. (required)
     * @param recipientId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> События трекинга. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ресурс не найден (или не принадлежит аккаунту). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRecipientTrackingAsync(String id, String recipientId, final ApiCallback<TrackingInfo> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRecipientTrackingValidateBeforeCall(id, recipientId, _callback);
        Type localVarReturnType = new TypeToken<TrackingInfo>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listLetters
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param status  (optional)
     * @param createdFrom  (optional)
     * @param createdTo  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Страница писем. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listLettersCall(Integer limit, Integer offset, LetterStatus status, OffsetDateTime createdFrom, OffsetDateTime createdTo, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/letters";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        if (createdFrom != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("created_from", createdFrom));
        }

        if (createdTo != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("created_to", createdTo));
        }

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listLettersValidateBeforeCall(Integer limit, Integer offset, LetterStatus status, OffsetDateTime createdFrom, OffsetDateTime createdTo, final ApiCallback _callback) throws ApiException {
        return listLettersCall(limit, offset, status, createdFrom, createdTo, _callback);

    }

    /**
     * Список писем
     * Письма аккаунта (все каналы — и API, и личный кабинет; канал указан в поле &#x60;channel&#x60;). Требуется scope &#x60;letters:read&#x60;.
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param status  (optional)
     * @param createdFrom  (optional)
     * @param createdTo  (optional)
     * @return ListLetters200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Страница писем. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
     </table>
     */
    public ListLetters200Response listLetters(Integer limit, Integer offset, LetterStatus status, OffsetDateTime createdFrom, OffsetDateTime createdTo) throws ApiException {
        ApiResponse<ListLetters200Response> localVarResp = listLettersWithHttpInfo(limit, offset, status, createdFrom, createdTo);
        return localVarResp.getData();
    }

    /**
     * Список писем
     * Письма аккаунта (все каналы — и API, и личный кабинет; канал указан в поле &#x60;channel&#x60;). Требуется scope &#x60;letters:read&#x60;.
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param status  (optional)
     * @param createdFrom  (optional)
     * @param createdTo  (optional)
     * @return ApiResponse&lt;ListLetters200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Страница писем. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListLetters200Response> listLettersWithHttpInfo(Integer limit, Integer offset, LetterStatus status, OffsetDateTime createdFrom, OffsetDateTime createdTo) throws ApiException {
        okhttp3.Call localVarCall = listLettersValidateBeforeCall(limit, offset, status, createdFrom, createdTo, null);
        Type localVarReturnType = new TypeToken<ListLetters200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Список писем (asynchronously)
     * Письма аккаунта (все каналы — и API, и личный кабинет; канал указан в поле &#x60;channel&#x60;). Требуется scope &#x60;letters:read&#x60;.
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param status  (optional)
     * @param createdFrom  (optional)
     * @param createdTo  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Страница писем. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Нет/неверный API-ключ, либо IP не в allowlist ключа. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> У ключа нет нужного scope. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listLettersAsync(Integer limit, Integer offset, LetterStatus status, OffsetDateTime createdFrom, OffsetDateTime createdTo, final ApiCallback<ListLetters200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = listLettersValidateBeforeCall(limit, offset, status, createdFrom, createdTo, _callback);
        Type localVarReturnType = new TypeToken<ListLetters200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
