/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.LetterClass;
import org.openapitools.client.model.LetterContent;
import org.openapitools.client.model.RecipientInput;
import org.openapitools.client.model.SenderInput;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateLetterRequest
 */
public class CreateLetterRequestTest {
    private final CreateLetterRequest model = new CreateLetterRequest();

    /**
     * Model tests for CreateLetterRequest
     */
    @Test
    public void testCreateLetterRequest() {
        // TODO: test CreateLetterRequest
    }

    /**
     * Test the property 'sender'
     */
    @Test
    public void senderTest() {
        // TODO: test sender
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    public void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'letterClass'
     */
    @Test
    public void letterClassTest() {
        // TODO: test letterClass
    }

    /**
     * Test the property 'promoCode'
     */
    @Test
    public void promoCodeTest() {
        // TODO: test promoCode
    }

    /**
     * Test the property 'onPromoInvalid'
     */
    @Test
    public void onPromoInvalidTest() {
        // TODO: test onPromoInvalid
    }

    /**
     * Test the property 'onInsufficientFunds'
     */
    @Test
    public void onInsufficientFundsTest() {
        // TODO: test onInsufficientFunds
    }

    /**
     * Test the property 'dryRun'
     */
    @Test
    public void dryRunTest() {
        // TODO: test dryRun
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

}
