/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhookEventData
 */
public class WebhookEventDataTest {
    private final WebhookEventData model = new WebhookEventData();

    /**
     * Model tests for WebhookEventData
     */
    @Test
    public void testWebhookEventData() {
        // TODO: test WebhookEventData
    }

    /**
     * Test the property 'letterId'
     */
    @Test
    public void letterIdTest() {
        // TODO: test letterId
    }

    /**
     * Test the property 'recipientId'
     */
    @Test
    public void recipientIdTest() {
        // TODO: test recipientId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'shipmentNumber'
     */
    @Test
    public void shipmentNumberTest() {
        // TODO: test shipmentNumber
    }

    /**
     * Test the property 'trackingNumber'
     */
    @Test
    public void trackingNumberTest() {
        // TODO: test trackingNumber
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'amountMinor'
     */
    @Test
    public void amountMinorTest() {
        // TODO: test amountMinor
    }

    /**
     * Test the property 'receiptPdf'
     */
    @Test
    public void receiptPdfTest() {
        // TODO: test receiptPdf
    }

    /**
     * Test the property 'receiptUrl'
     */
    @Test
    public void receiptUrlTest() {
        // TODO: test receiptUrl
    }

    /**
     * Test the property 'inventoryPdf'
     */
    @Test
    public void inventoryPdfTest() {
        // TODO: test inventoryPdf
    }

}
