/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.LetterClass;
import org.openapitools.client.model.LetterContent;
import org.openapitools.client.model.RecipientInput;
import org.openapitools.client.model.SenderInput;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ru.doslano.sdk.JSON;

/**
 * CreateLetterRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-29T12:14:24.598854985Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class CreateLetterRequest {
  public static final String SERIALIZED_NAME_SENDER = "sender";
  @SerializedName(SERIALIZED_NAME_SENDER)
  @javax.annotation.Nullable
  private SenderInput sender;

  public static final String SERIALIZED_NAME_RECIPIENTS = "recipients";
  @SerializedName(SERIALIZED_NAME_RECIPIENTS)
  @javax.annotation.Nonnull
  private List<RecipientInput> recipients = new ArrayList<>();

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nonnull
  private LetterContent content;

  public static final String SERIALIZED_NAME_LETTER_CLASS = "letter_class";
  @SerializedName(SERIALIZED_NAME_LETTER_CLASS)
  @javax.annotation.Nullable
  private LetterClass letterClass = LetterClass.REGISTERED;

  public static final String SERIALIZED_NAME_PROMO_CODE = "promo_code";
  @SerializedName(SERIALIZED_NAME_PROMO_CODE)
  @javax.annotation.Nullable
  private String promoCode;

  /**
   * Что делать, если промокод не применился: &#x60;ignore&#x60; — отправить без скидки и вернуть пометку в &#x60;pricing.promo&#x60;; &#x60;reject&#x60; — отклонить (422). 
   */
  @JsonAdapter(OnPromoInvalidEnum.Adapter.class)
  public enum OnPromoInvalidEnum {
    IGNORE("ignore"),
    
    REJECT("reject");

    private String value;

    OnPromoInvalidEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OnPromoInvalidEnum fromValue(String value) {
      for (OnPromoInvalidEnum b : OnPromoInvalidEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OnPromoInvalidEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OnPromoInvalidEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OnPromoInvalidEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OnPromoInvalidEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      OnPromoInvalidEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ON_PROMO_INVALID = "on_promo_invalid";
  @SerializedName(SERIALIZED_NAME_ON_PROMO_INVALID)
  @javax.annotation.Nullable
  private OnPromoInvalidEnum onPromoInvalid = OnPromoInvalidEnum.IGNORE;

  /**
   * Что делать при нехватке средств: &#x60;reject&#x60; — отклонить (402), письмо не создаётся; &#x60;hold&#x60; — создать письмо в статусе &#x60;awaiting_payment&#x60;, оно оплатится автоматически при пополнении баланса. 
   */
  @JsonAdapter(OnInsufficientFundsEnum.Adapter.class)
  public enum OnInsufficientFundsEnum {
    REJECT("reject"),
    
    HOLD("hold");

    private String value;

    OnInsufficientFundsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OnInsufficientFundsEnum fromValue(String value) {
      for (OnInsufficientFundsEnum b : OnInsufficientFundsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OnInsufficientFundsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OnInsufficientFundsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OnInsufficientFundsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OnInsufficientFundsEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      OnInsufficientFundsEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ON_INSUFFICIENT_FUNDS = "on_insufficient_funds";
  @SerializedName(SERIALIZED_NAME_ON_INSUFFICIENT_FUNDS)
  @javax.annotation.Nullable
  private OnInsufficientFundsEnum onInsufficientFunds = OnInsufficientFundsEnum.REJECT;

  public static final String SERIALIZED_NAME_DRY_RUN = "dry_run";
  @SerializedName(SERIALIZED_NAME_DRY_RUN)
  @javax.annotation.Nullable
  private Boolean dryRun = false;

  public static final String SERIALIZED_NAME_CALLBACK_URL = "callback_url";
  @SerializedName(SERIALIZED_NAME_CALLBACK_URL)
  @javax.annotation.Nullable
  private URI callbackUrl;

  public CreateLetterRequest() {
  }

  public CreateLetterRequest sender(@javax.annotation.Nullable SenderInput sender) {
    this.sender = sender;
    return this;
  }

  /**
   * Отправитель. Если не указан — берётся отправитель по умолчанию из профиля аккаунта.
   * @return sender
   */
  @javax.annotation.Nullable
  public SenderInput getSender() {
    return sender;
  }

  public void setSender(@javax.annotation.Nullable SenderInput sender) {
    this.sender = sender;
  }


  public CreateLetterRequest recipients(@javax.annotation.Nonnull List<RecipientInput> recipients) {
    this.recipients = recipients;
    return this;
  }

  public CreateLetterRequest addRecipientsItem(RecipientInput recipientsItem) {
    if (this.recipients == null) {
      this.recipients = new ArrayList<>();
    }
    this.recipients.add(recipientsItem);
    return this;
  }

  /**
   * Get recipients
   * @return recipients
   */
  @javax.annotation.Nonnull
  public List<RecipientInput> getRecipients() {
    return recipients;
  }

  public void setRecipients(@javax.annotation.Nonnull List<RecipientInput> recipients) {
    this.recipients = recipients;
  }


  public CreateLetterRequest content(@javax.annotation.Nonnull LetterContent content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nonnull
  public LetterContent getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nonnull LetterContent content) {
    this.content = content;
  }


  public CreateLetterRequest letterClass(@javax.annotation.Nullable LetterClass letterClass) {
    this.letterClass = letterClass;
    return this;
  }

  /**
   * Get letterClass
   * @return letterClass
   */
  @javax.annotation.Nullable
  public LetterClass getLetterClass() {
    return letterClass;
  }

  public void setLetterClass(@javax.annotation.Nullable LetterClass letterClass) {
    this.letterClass = letterClass;
  }


  public CreateLetterRequest promoCode(@javax.annotation.Nullable String promoCode) {
    this.promoCode = promoCode;
    return this;
  }

  /**
   * Промокод (опционально).
   * @return promoCode
   */
  @javax.annotation.Nullable
  public String getPromoCode() {
    return promoCode;
  }

  public void setPromoCode(@javax.annotation.Nullable String promoCode) {
    this.promoCode = promoCode;
  }


  public CreateLetterRequest onPromoInvalid(@javax.annotation.Nullable OnPromoInvalidEnum onPromoInvalid) {
    this.onPromoInvalid = onPromoInvalid;
    return this;
  }

  /**
   * Что делать, если промокод не применился: &#x60;ignore&#x60; — отправить без скидки и вернуть пометку в &#x60;pricing.promo&#x60;; &#x60;reject&#x60; — отклонить (422). 
   * @return onPromoInvalid
   */
  @javax.annotation.Nullable
  public OnPromoInvalidEnum getOnPromoInvalid() {
    return onPromoInvalid;
  }

  public void setOnPromoInvalid(@javax.annotation.Nullable OnPromoInvalidEnum onPromoInvalid) {
    this.onPromoInvalid = onPromoInvalid;
  }


  public CreateLetterRequest onInsufficientFunds(@javax.annotation.Nullable OnInsufficientFundsEnum onInsufficientFunds) {
    this.onInsufficientFunds = onInsufficientFunds;
    return this;
  }

  /**
   * Что делать при нехватке средств: &#x60;reject&#x60; — отклонить (402), письмо не создаётся; &#x60;hold&#x60; — создать письмо в статусе &#x60;awaiting_payment&#x60;, оно оплатится автоматически при пополнении баланса. 
   * @return onInsufficientFunds
   */
  @javax.annotation.Nullable
  public OnInsufficientFundsEnum getOnInsufficientFunds() {
    return onInsufficientFunds;
  }

  public void setOnInsufficientFunds(@javax.annotation.Nullable OnInsufficientFundsEnum onInsufficientFunds) {
    this.onInsufficientFunds = onInsufficientFunds;
  }


  public CreateLetterRequest dryRun(@javax.annotation.Nullable Boolean dryRun) {
    this.dryRun = dryRun;
    return this;
  }

  /**
   * Пробный прогон: запрос проходит ПОЛНУЮ реальную валидацию (ключ, scope, IP, файлы, адреса получателей, промокод) и возвращает расчёт цены — но письмо в итоге не создаётся и средства не списываются. Ответ — &#x60;200&#x60; со схемой &#x60;DryRunResult&#x60; (вместо &#x60;201&#x60;/&#x60;Letter&#x60;). Ошибки валидации возвращаются теми же кодами, что и при реальной отправке (400/422) — это честный тест интеграции. &#x60;Idempotency-Key&#x60; при &#x60;dry_run&#x60; игнорируется; &#x60;callback_url&#x60; не регистрируется; баланс НЕ проверяется (тестируйте хоть с нулевым балансом — сумма к списанию будет в &#x60;pricing.total_minor&#x60;). 
   * @return dryRun
   */
  @javax.annotation.Nullable
  public Boolean getDryRun() {
    return dryRun;
  }

  public void setDryRun(@javax.annotation.Nullable Boolean dryRun) {
    this.dryRun = dryRun;
  }


  public CreateLetterRequest callbackUrl(@javax.annotation.Nullable URI callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

  /**
   * HTTPS-URL для колбеков по этому письму. Если не указан — используйте поллинг.
   * @return callbackUrl
   */
  @javax.annotation.Nullable
  public URI getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(@javax.annotation.Nullable URI callbackUrl) {
    this.callbackUrl = callbackUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateLetterRequest createLetterRequest = (CreateLetterRequest) o;
    return Objects.equals(this.sender, createLetterRequest.sender) &&
        Objects.equals(this.recipients, createLetterRequest.recipients) &&
        Objects.equals(this.content, createLetterRequest.content) &&
        Objects.equals(this.letterClass, createLetterRequest.letterClass) &&
        Objects.equals(this.promoCode, createLetterRequest.promoCode) &&
        Objects.equals(this.onPromoInvalid, createLetterRequest.onPromoInvalid) &&
        Objects.equals(this.onInsufficientFunds, createLetterRequest.onInsufficientFunds) &&
        Objects.equals(this.dryRun, createLetterRequest.dryRun) &&
        Objects.equals(this.callbackUrl, createLetterRequest.callbackUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sender, recipients, content, letterClass, promoCode, onPromoInvalid, onInsufficientFunds, dryRun, callbackUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateLetterRequest {\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    letterClass: ").append(toIndentedString(letterClass)).append("\n");
    sb.append("    promoCode: ").append(toIndentedString(promoCode)).append("\n");
    sb.append("    onPromoInvalid: ").append(toIndentedString(onPromoInvalid)).append("\n");
    sb.append("    onInsufficientFunds: ").append(toIndentedString(onInsufficientFunds)).append("\n");
    sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sender");
    openapiFields.add("recipients");
    openapiFields.add("content");
    openapiFields.add("letter_class");
    openapiFields.add("promo_code");
    openapiFields.add("on_promo_invalid");
    openapiFields.add("on_insufficient_funds");
    openapiFields.add("dry_run");
    openapiFields.add("callback_url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("recipients");
    openapiRequiredFields.add("content");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateLetterRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateLetterRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateLetterRequest is not found in the empty JSON string", CreateLetterRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateLetterRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateLetterRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateLetterRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `sender`
      if (jsonObj.get("sender") != null && !jsonObj.get("sender").isJsonNull()) {
        SenderInput.validateJsonElement(jsonObj.get("sender"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("recipients").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `recipients` to be an array in the JSON string but got `%s`", jsonObj.get("recipients").toString()));
      }

      JsonArray jsonArrayrecipients = jsonObj.getAsJsonArray("recipients");
      // validate the required field `recipients` (array)
      for (int i = 0; i < jsonArrayrecipients.size(); i++) {
        RecipientInput.validateJsonElement(jsonArrayrecipients.get(i));
      };
      // validate the required field `content`
      LetterContent.validateJsonElement(jsonObj.get("content"));
      // validate the optional field `letter_class`
      if (jsonObj.get("letter_class") != null && !jsonObj.get("letter_class").isJsonNull()) {
        LetterClass.validateJsonElement(jsonObj.get("letter_class"));
      }
      if ((jsonObj.get("promo_code") != null && !jsonObj.get("promo_code").isJsonNull()) && !jsonObj.get("promo_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `promo_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("promo_code").toString()));
      }
      if ((jsonObj.get("on_promo_invalid") != null && !jsonObj.get("on_promo_invalid").isJsonNull()) && !jsonObj.get("on_promo_invalid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `on_promo_invalid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("on_promo_invalid").toString()));
      }
      // validate the optional field `on_promo_invalid`
      if (jsonObj.get("on_promo_invalid") != null && !jsonObj.get("on_promo_invalid").isJsonNull()) {
        OnPromoInvalidEnum.validateJsonElement(jsonObj.get("on_promo_invalid"));
      }
      if ((jsonObj.get("on_insufficient_funds") != null && !jsonObj.get("on_insufficient_funds").isJsonNull()) && !jsonObj.get("on_insufficient_funds").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `on_insufficient_funds` to be a primitive type in the JSON string but got `%s`", jsonObj.get("on_insufficient_funds").toString()));
      }
      // validate the optional field `on_insufficient_funds`
      if (jsonObj.get("on_insufficient_funds") != null && !jsonObj.get("on_insufficient_funds").isJsonNull()) {
        OnInsufficientFundsEnum.validateJsonElement(jsonObj.get("on_insufficient_funds"));
      }
      if ((jsonObj.get("callback_url") != null && !jsonObj.get("callback_url").isJsonNull()) && !jsonObj.get("callback_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `callback_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("callback_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateLetterRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateLetterRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateLetterRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateLetterRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateLetterRequest>() {
           @Override
           public void write(JsonWriter out, CreateLetterRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateLetterRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateLetterRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateLetterRequest
   * @throws IOException if the JSON string is invalid with respect to CreateLetterRequest
   */
  public static CreateLetterRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateLetterRequest.class);
  }

  /**
   * Convert an instance of CreateLetterRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

