/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DryRunResultPricing;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ru.doslano.sdk.JSON;

/**
 * Результат пробного прогона (&#x60;dry_run: true&#x60;): запрос полностью валиден. Письмо НЕ создано, средства НЕ списаны. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-28T12:58:29.771736505Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class DryRunResult {
  public static final String SERIALIZED_NAME_DRY_RUN = "dry_run";
  @SerializedName(SERIALIZED_NAME_DRY_RUN)
  @javax.annotation.Nonnull
  private Boolean dryRun;

  public static final String SERIALIZED_NAME_VALID = "valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  @javax.annotation.Nonnull
  private Boolean valid;

  public static final String SERIALIZED_NAME_RECIPIENTS_COUNT = "recipients_count";
  @SerializedName(SERIALIZED_NAME_RECIPIENTS_COUNT)
  @javax.annotation.Nonnull
  private Integer recipientsCount;

  public static final String SERIALIZED_NAME_PRICING = "pricing";
  @SerializedName(SERIALIZED_NAME_PRICING)
  @javax.annotation.Nonnull
  private DryRunResultPricing pricing;

  public DryRunResult() {
  }

  public DryRunResult dryRun(@javax.annotation.Nonnull Boolean dryRun) {
    this.dryRun = dryRun;
    return this;
  }

  /**
   * Всегда &#x60;true&#x60; (маркер ответа пробного прогона).
   * @return dryRun
   */
  @javax.annotation.Nonnull
  public Boolean getDryRun() {
    return dryRun;
  }

  public void setDryRun(@javax.annotation.Nonnull Boolean dryRun) {
    this.dryRun = dryRun;
  }


  public DryRunResult valid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
    return this;
  }

  /**
   * Всегда &#x60;true&#x60; — невалидные запросы получают 400/422.
   * @return valid
   */
  @javax.annotation.Nonnull
  public Boolean getValid() {
    return valid;
  }

  public void setValid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
  }


  public DryRunResult recipientsCount(@javax.annotation.Nonnull Integer recipientsCount) {
    this.recipientsCount = recipientsCount;
    return this;
  }

  /**
   * Количество получателей (&#x3D; отправлений) в запросе.
   * @return recipientsCount
   */
  @javax.annotation.Nonnull
  public Integer getRecipientsCount() {
    return recipientsCount;
  }

  public void setRecipientsCount(@javax.annotation.Nonnull Integer recipientsCount) {
    this.recipientsCount = recipientsCount;
  }


  public DryRunResult pricing(@javax.annotation.Nonnull DryRunResultPricing pricing) {
    this.pricing = pricing;
    return this;
  }

  /**
   * Get pricing
   * @return pricing
   */
  @javax.annotation.Nonnull
  public DryRunResultPricing getPricing() {
    return pricing;
  }

  public void setPricing(@javax.annotation.Nonnull DryRunResultPricing pricing) {
    this.pricing = pricing;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DryRunResult dryRunResult = (DryRunResult) o;
    return Objects.equals(this.dryRun, dryRunResult.dryRun) &&
        Objects.equals(this.valid, dryRunResult.valid) &&
        Objects.equals(this.recipientsCount, dryRunResult.recipientsCount) &&
        Objects.equals(this.pricing, dryRunResult.pricing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dryRun, valid, recipientsCount, pricing);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DryRunResult {\n");
    sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    recipientsCount: ").append(toIndentedString(recipientsCount)).append("\n");
    sb.append("    pricing: ").append(toIndentedString(pricing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dry_run");
    openapiFields.add("valid");
    openapiFields.add("recipients_count");
    openapiFields.add("pricing");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("dry_run");
    openapiRequiredFields.add("valid");
    openapiRequiredFields.add("recipients_count");
    openapiRequiredFields.add("pricing");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DryRunResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DryRunResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DryRunResult is not found in the empty JSON string", DryRunResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DryRunResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DryRunResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DryRunResult.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `pricing`
      DryRunResultPricing.validateJsonElement(jsonObj.get("pricing"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DryRunResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DryRunResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DryRunResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DryRunResult.class));

       return (TypeAdapter<T>) new TypeAdapter<DryRunResult>() {
           @Override
           public void write(JsonWriter out, DryRunResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DryRunResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DryRunResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DryRunResult
   * @throws IOException if the JSON string is invalid with respect to DryRunResult
   */
  public static DryRunResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DryRunResult.class);
  }

  /**
   * Convert an instance of DryRunResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

