/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PromoResult;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ru.doslano.sdk.JSON;

/**
 * Расчёт к списанию при реальной отправке этого запроса.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-19T16:13:19.102645023Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class DryRunResultPricing {
  public static final String SERIALIZED_NAME_SUBTOTAL_MINOR = "subtotal_minor";
  @SerializedName(SERIALIZED_NAME_SUBTOTAL_MINOR)
  @javax.annotation.Nonnull
  private Long subtotalMinor;

  public static final String SERIALIZED_NAME_TOTAL_MINOR = "total_minor";
  @SerializedName(SERIALIZED_NAME_TOTAL_MINOR)
  @javax.annotation.Nonnull
  private Long totalMinor;

  /**
   * Gets or Sets currency
   */
  @JsonAdapter(CurrencyEnum.Adapter.class)
  public enum CurrencyEnum {
    RUB("RUB");

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CurrencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CurrencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CurrencyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CurrencyEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CurrencyEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nonnull
  private CurrencyEnum currency;

  public static final String SERIALIZED_NAME_PROMO = "promo";
  @SerializedName(SERIALIZED_NAME_PROMO)
  @javax.annotation.Nullable
  private PromoResult promo;

  public DryRunResultPricing() {
  }

  public DryRunResultPricing subtotalMinor(@javax.annotation.Nonnull Long subtotalMinor) {
    this.subtotalMinor = subtotalMinor;
    return this;
  }

  /**
   * Цена без скидки, в копейках.
   * @return subtotalMinor
   */
  @javax.annotation.Nonnull
  public Long getSubtotalMinor() {
    return subtotalMinor;
  }

  public void setSubtotalMinor(@javax.annotation.Nonnull Long subtotalMinor) {
    this.subtotalMinor = subtotalMinor;
  }


  public DryRunResultPricing totalMinor(@javax.annotation.Nonnull Long totalMinor) {
    this.totalMinor = totalMinor;
    return this;
  }

  /**
   * Итог к списанию (после промокода), в копейках. Non-binding — фиксируется при реальной оплате.
   * @return totalMinor
   */
  @javax.annotation.Nonnull
  public Long getTotalMinor() {
    return totalMinor;
  }

  public void setTotalMinor(@javax.annotation.Nonnull Long totalMinor) {
    this.totalMinor = totalMinor;
  }


  public DryRunResultPricing currency(@javax.annotation.Nonnull CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nonnull
  public CurrencyEnum getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nonnull CurrencyEnum currency) {
    this.currency = currency;
  }


  public DryRunResultPricing promo(@javax.annotation.Nullable PromoResult promo) {
    this.promo = promo;
    return this;
  }

  /**
   * Get promo
   * @return promo
   */
  @javax.annotation.Nullable
  public PromoResult getPromo() {
    return promo;
  }

  public void setPromo(@javax.annotation.Nullable PromoResult promo) {
    this.promo = promo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DryRunResultPricing dryRunResultPricing = (DryRunResultPricing) o;
    return Objects.equals(this.subtotalMinor, dryRunResultPricing.subtotalMinor) &&
        Objects.equals(this.totalMinor, dryRunResultPricing.totalMinor) &&
        Objects.equals(this.currency, dryRunResultPricing.currency) &&
        Objects.equals(this.promo, dryRunResultPricing.promo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subtotalMinor, totalMinor, currency, promo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DryRunResultPricing {\n");
    sb.append("    subtotalMinor: ").append(toIndentedString(subtotalMinor)).append("\n");
    sb.append("    totalMinor: ").append(toIndentedString(totalMinor)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    promo: ").append(toIndentedString(promo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("subtotal_minor");
    openapiFields.add("total_minor");
    openapiFields.add("currency");
    openapiFields.add("promo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("subtotal_minor");
    openapiRequiredFields.add("total_minor");
    openapiRequiredFields.add("currency");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DryRunResultPricing
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DryRunResultPricing.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DryRunResultPricing is not found in the empty JSON string", DryRunResultPricing.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DryRunResultPricing.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DryRunResultPricing` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DryRunResultPricing.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      // validate the required field `currency`
      CurrencyEnum.validateJsonElement(jsonObj.get("currency"));
      // validate the optional field `promo`
      if (jsonObj.get("promo") != null && !jsonObj.get("promo").isJsonNull()) {
        PromoResult.validateJsonElement(jsonObj.get("promo"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DryRunResultPricing.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DryRunResultPricing' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DryRunResultPricing> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DryRunResultPricing.class));

       return (TypeAdapter<T>) new TypeAdapter<DryRunResultPricing>() {
           @Override
           public void write(JsonWriter out, DryRunResultPricing value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DryRunResultPricing read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DryRunResultPricing given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DryRunResultPricing
   * @throws IOException if the JSON string is invalid with respect to DryRunResultPricing
   */
  public static DryRunResultPricing fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DryRunResultPricing.class);
  }

  /**
   * Convert an instance of DryRunResultPricing to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

