/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ru.doslano.sdk.JSON;

/**
 * Источник PDF-файла. Укажите **ровно один** способ: - &#x60;base64&#x60; — содержимое файла в base64 (для небольших файлов); - &#x60;url&#x60; — HTTPS-ссылка, файл скачивается потоково (для крупных файлов,   чтобы не передавать тело в base64). Лимиты по размеру/страницам — см. документацию; тип файла — только PDF. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-11T11:05:00.528130304Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class FileSource {
  public static final String SERIALIZED_NAME_BASE64 = "base64";
  @SerializedName(SERIALIZED_NAME_BASE64)
  @javax.annotation.Nullable
  private String base64;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nullable
  private URI url;

  public static final String SERIALIZED_NAME_FILENAME = "filename";
  @SerializedName(SERIALIZED_NAME_FILENAME)
  @javax.annotation.Nullable
  private String filename;

  public FileSource() {
  }

  public FileSource base64(@javax.annotation.Nullable String base64) {
    this.base64 = base64;
    return this;
  }

  /**
   * PDF в base64.
   * @return base64
   */
  @javax.annotation.Nullable
  public String getBase64() {
    return base64;
  }

  public void setBase64(@javax.annotation.Nullable String base64) {
    this.base64 = base64;
  }


  public FileSource url(@javax.annotation.Nullable URI url) {
    this.url = url;
    return this;
  }

  /**
   * HTTPS-ссылка на PDF (скачиваем потоково).
   * @return url
   */
  @javax.annotation.Nullable
  public URI getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nullable URI url) {
    this.url = url;
  }


  public FileSource filename(@javax.annotation.Nullable String filename) {
    this.filename = filename;
    return this;
  }

  /**
   * Имя файла (опционально, для отображения).
   * @return filename
   */
  @javax.annotation.Nullable
  public String getFilename() {
    return filename;
  }

  public void setFilename(@javax.annotation.Nullable String filename) {
    this.filename = filename;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileSource fileSource = (FileSource) o;
    return Objects.equals(this.base64, fileSource.base64) &&
        Objects.equals(this.url, fileSource.url) &&
        Objects.equals(this.filename, fileSource.filename);
  }

  @Override
  public int hashCode() {
    return Objects.hash(base64, url, filename);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileSource {\n");
    sb.append("    base64: ").append(toIndentedString(base64)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("base64");
    openapiFields.add("url");
    openapiFields.add("filename");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FileSource
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FileSource.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FileSource is not found in the empty JSON string", FileSource.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FileSource.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FileSource` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("base64") != null && !jsonObj.get("base64").isJsonNull()) && !jsonObj.get("base64").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `base64` to be a primitive type in the JSON string but got `%s`", jsonObj.get("base64").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("filename") != null && !jsonObj.get("filename").isJsonNull()) && !jsonObj.get("filename").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `filename` to be a primitive type in the JSON string but got `%s`", jsonObj.get("filename").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FileSource.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FileSource' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FileSource> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FileSource.class));

       return (TypeAdapter<T>) new TypeAdapter<FileSource>() {
           @Override
           public void write(JsonWriter out, FileSource value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FileSource read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FileSource given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FileSource
   * @throws IOException if the JSON string is invalid with respect to FileSource
   */
  public static FileSource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FileSource.class);
  }

  /**
   * Convert an instance of FileSource to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

