/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.openapitools.client.model.RecipientStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ru.doslano.sdk.JSON;

/**
 * Recipient
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-28T12:58:29.771736505Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class Recipient {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private String address;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private RecipientStatus status;

  public static final String SERIALIZED_NAME_SHIPMENT_NUMBER = "shipment_number";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_NUMBER)
  @javax.annotation.Nullable
  private String shipmentNumber;

  public static final String SERIALIZED_NAME_TRACKING_NUMBER = "tracking_number";
  @SerializedName(SERIALIZED_NAME_TRACKING_NUMBER)
  @javax.annotation.Nullable
  private String trackingNumber;

  public static final String SERIALIZED_NAME_PRICE_MINOR = "price_minor";
  @SerializedName(SERIALIZED_NAME_PRICE_MINOR)
  @javax.annotation.Nullable
  private Long priceMinor;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @javax.annotation.Nullable
  private String error;

  public static final String SERIALIZED_NAME_RECEIPT_PDF = "receipt_pdf";
  @SerializedName(SERIALIZED_NAME_RECEIPT_PDF)
  @javax.annotation.Nullable
  private URI receiptPdf;

  public static final String SERIALIZED_NAME_RECEIPT_URL = "receipt_url";
  @SerializedName(SERIALIZED_NAME_RECEIPT_URL)
  @javax.annotation.Nullable
  private URI receiptUrl;

  public static final String SERIALIZED_NAME_INVENTORY_PDF = "inventory_pdf";
  @SerializedName(SERIALIZED_NAME_INVENTORY_PDF)
  @javax.annotation.Nullable
  private URI inventoryPdf;

  public Recipient() {
  }

  public Recipient id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public Recipient name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Recipient address(@javax.annotation.Nullable String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  public String getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }


  public Recipient status(@javax.annotation.Nonnull RecipientStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public RecipientStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull RecipientStatus status) {
    this.status = status;
  }


  public Recipient shipmentNumber(@javax.annotation.Nullable String shipmentNumber) {
    this.shipmentNumber = shipmentNumber;
    return this;
  }

  /**
   * Наш трек-номер (РПО), присваивается сразу при создании.
   * @return shipmentNumber
   */
  @javax.annotation.Nullable
  public String getShipmentNumber() {
    return shipmentNumber;
  }

  public void setShipmentNumber(@javax.annotation.Nullable String shipmentNumber) {
    this.shipmentNumber = shipmentNumber;
  }


  public Recipient trackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

  /**
   * Трек-номер Почты России (ШПИ). Появляется после регистрации отправления.
   * @return trackingNumber
   */
  @javax.annotation.Nullable
  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }


  public Recipient priceMinor(@javax.annotation.Nullable Long priceMinor) {
    this.priceMinor = priceMinor;
    return this;
  }

  /**
   * Стоимость отправления этому получателю, в копейках.
   * @return priceMinor
   */
  @javax.annotation.Nullable
  public Long getPriceMinor() {
    return priceMinor;
  }

  public void setPriceMinor(@javax.annotation.Nullable Long priceMinor) {
    this.priceMinor = priceMinor;
  }


  public Recipient error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Причина ошибки (для &#x60;failed&#x60;).
   * @return error
   */
  @javax.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  public Recipient receiptPdf(@javax.annotation.Nullable URI receiptPdf) {
    this.receiptPdf = receiptPdf;
    return this;
  }

  /**
   * Ссылка на скачивание PDF фискального чека (54-ФЗ) этому получателю через наш API (см. &#x60;GET /v1/letters/{id}/recipients/{recipient_id}/receipt.pdf&#x60;). Присутствует, только когда чек пробит и его PDF сохранён у нас (получатель в статусе &#x60;sent&#x60;/&#x60;delivered&#x60;).
   * @return receiptPdf
   */
  @javax.annotation.Nullable
  public URI getReceiptPdf() {
    return receiptPdf;
  }

  public void setReceiptPdf(@javax.annotation.Nullable URI receiptPdf) {
    this.receiptPdf = receiptPdf;
  }


  public Recipient receiptUrl(@javax.annotation.Nullable URI receiptUrl) {
    this.receiptUrl = receiptUrl;
    return this;
  }

  /**
   * Ссылка на фискальный чек на сайте ОФД (1-ОФД). Присутствует, когда чек пробит (получатель &#x60;sent&#x60;/&#x60;delivered&#x60;). Может присутствовать и без &#x60;receipt_pdf&#x60; — когда наш PDF недоступен (link_only).
   * @return receiptUrl
   */
  @javax.annotation.Nullable
  public URI getReceiptUrl() {
    return receiptUrl;
  }

  public void setReceiptUrl(@javax.annotation.Nullable URI receiptUrl) {
    this.receiptUrl = receiptUrl;
  }


  public Recipient inventoryPdf(@javax.annotation.Nullable URI inventoryPdf) {
    this.inventoryPdf = inventoryPdf;
    return this;
  }

  /**
   * Ссылка на скачивание PDF описи вложения (форма 107, версия отправителя) через наш API (см. &#x60;GET /v1/letters/{id}/recipients/{recipient_id}/inventory.pdf&#x60;). Присутствует, когда опись сформирована и отправление передано в Почту (получатель в статусе &#x60;sent&#x60;/&#x60;delivered&#x60;).
   * @return inventoryPdf
   */
  @javax.annotation.Nullable
  public URI getInventoryPdf() {
    return inventoryPdf;
  }

  public void setInventoryPdf(@javax.annotation.Nullable URI inventoryPdf) {
    this.inventoryPdf = inventoryPdf;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recipient recipient = (Recipient) o;
    return Objects.equals(this.id, recipient.id) &&
        Objects.equals(this.name, recipient.name) &&
        Objects.equals(this.address, recipient.address) &&
        Objects.equals(this.status, recipient.status) &&
        Objects.equals(this.shipmentNumber, recipient.shipmentNumber) &&
        Objects.equals(this.trackingNumber, recipient.trackingNumber) &&
        Objects.equals(this.priceMinor, recipient.priceMinor) &&
        Objects.equals(this.error, recipient.error) &&
        Objects.equals(this.receiptPdf, recipient.receiptPdf) &&
        Objects.equals(this.receiptUrl, recipient.receiptUrl) &&
        Objects.equals(this.inventoryPdf, recipient.inventoryPdf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, address, status, shipmentNumber, trackingNumber, priceMinor, error, receiptPdf, receiptUrl, inventoryPdf);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recipient {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    shipmentNumber: ").append(toIndentedString(shipmentNumber)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    priceMinor: ").append(toIndentedString(priceMinor)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    receiptPdf: ").append(toIndentedString(receiptPdf)).append("\n");
    sb.append("    receiptUrl: ").append(toIndentedString(receiptUrl)).append("\n");
    sb.append("    inventoryPdf: ").append(toIndentedString(inventoryPdf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("address");
    openapiFields.add("status");
    openapiFields.add("shipment_number");
    openapiFields.add("tracking_number");
    openapiFields.add("price_minor");
    openapiFields.add("error");
    openapiFields.add("receipt_pdf");
    openapiFields.add("receipt_url");
    openapiFields.add("inventory_pdf");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("status");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Recipient
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Recipient.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Recipient is not found in the empty JSON string", Recipient.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Recipient.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Recipient` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Recipient.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) && !jsonObj.get("address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address").toString()));
      }
      // validate the required field `status`
      RecipientStatus.validateJsonElement(jsonObj.get("status"));
      if ((jsonObj.get("shipment_number") != null && !jsonObj.get("shipment_number").isJsonNull()) && !jsonObj.get("shipment_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipment_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipment_number").toString()));
      }
      if ((jsonObj.get("tracking_number") != null && !jsonObj.get("tracking_number").isJsonNull()) && !jsonObj.get("tracking_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tracking_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tracking_number").toString()));
      }
      if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
      if ((jsonObj.get("receipt_pdf") != null && !jsonObj.get("receipt_pdf").isJsonNull()) && !jsonObj.get("receipt_pdf").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `receipt_pdf` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receipt_pdf").toString()));
      }
      if ((jsonObj.get("receipt_url") != null && !jsonObj.get("receipt_url").isJsonNull()) && !jsonObj.get("receipt_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `receipt_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receipt_url").toString()));
      }
      if ((jsonObj.get("inventory_pdf") != null && !jsonObj.get("inventory_pdf").isJsonNull()) && !jsonObj.get("inventory_pdf").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `inventory_pdf` to be a primitive type in the JSON string but got `%s`", jsonObj.get("inventory_pdf").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Recipient.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Recipient' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Recipient> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Recipient.class));

       return (TypeAdapter<T>) new TypeAdapter<Recipient>() {
           @Override
           public void write(JsonWriter out, Recipient value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Recipient read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Recipient given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Recipient
   * @throws IOException if the JSON string is invalid with respect to Recipient
   */
  public static Recipient fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Recipient.class);
  }

  /**
   * Convert an instance of Recipient to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

