/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ru.doslano.sdk.JSON;

/**
 * WebhookEventData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-19T19:46:17.954263897Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class WebhookEventData {
  public static final String SERIALIZED_NAME_LETTER_ID = "letter_id";
  @SerializedName(SERIALIZED_NAME_LETTER_ID)
  @javax.annotation.Nonnull
  private String letterId;

  public static final String SERIALIZED_NAME_RECIPIENT_ID = "recipient_id";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_ID)
  @javax.annotation.Nullable
  private String recipientId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private String status;

  public static final String SERIALIZED_NAME_SHIPMENT_NUMBER = "shipment_number";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_NUMBER)
  @javax.annotation.Nullable
  private String shipmentNumber;

  public static final String SERIALIZED_NAME_TRACKING_NUMBER = "tracking_number";
  @SerializedName(SERIALIZED_NAME_TRACKING_NUMBER)
  @javax.annotation.Nullable
  private String trackingNumber;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @javax.annotation.Nullable
  private String error;

  public static final String SERIALIZED_NAME_AMOUNT_MINOR = "amount_minor";
  @SerializedName(SERIALIZED_NAME_AMOUNT_MINOR)
  @javax.annotation.Nullable
  private Integer amountMinor;

  public WebhookEventData() {
  }

  public WebhookEventData letterId(@javax.annotation.Nonnull String letterId) {
    this.letterId = letterId;
    return this;
  }

  /**
   * Get letterId
   * @return letterId
   */
  @javax.annotation.Nonnull
  public String getLetterId() {
    return letterId;
  }

  public void setLetterId(@javax.annotation.Nonnull String letterId) {
    this.letterId = letterId;
  }


  public WebhookEventData recipientId(@javax.annotation.Nullable String recipientId) {
    this.recipientId = recipientId;
    return this;
  }

  /**
   * Get recipientId
   * @return recipientId
   */
  @javax.annotation.Nullable
  public String getRecipientId() {
    return recipientId;
  }

  public void setRecipientId(@javax.annotation.Nullable String recipientId) {
    this.recipientId = recipientId;
  }


  public WebhookEventData status(@javax.annotation.Nonnull String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
  }


  public WebhookEventData shipmentNumber(@javax.annotation.Nullable String shipmentNumber) {
    this.shipmentNumber = shipmentNumber;
    return this;
  }

  /**
   * Get shipmentNumber
   * @return shipmentNumber
   */
  @javax.annotation.Nullable
  public String getShipmentNumber() {
    return shipmentNumber;
  }

  public void setShipmentNumber(@javax.annotation.Nullable String shipmentNumber) {
    this.shipmentNumber = shipmentNumber;
  }


  public WebhookEventData trackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

  /**
   * Get trackingNumber
   * @return trackingNumber
   */
  @javax.annotation.Nullable
  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(@javax.annotation.Nullable String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }


  public WebhookEventData error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  public WebhookEventData amountMinor(@javax.annotation.Nullable Integer amountMinor) {
    this.amountMinor = amountMinor;
    return this;
  }

  /**
   * Фактически списанная стоимость отправления ЭТОМУ получателю, в копейках (доля дисконтированного тотала письма с учётом промокода). Присутствует только в &#x60;recipient.sent&#x60; — отправление реально ушло и оплачено. В &#x60;recipient.failed&#x60; отсутствует: при провале сумма возвращается на баланс.
   * @return amountMinor
   */
  @javax.annotation.Nullable
  public Integer getAmountMinor() {
    return amountMinor;
  }

  public void setAmountMinor(@javax.annotation.Nullable Integer amountMinor) {
    this.amountMinor = amountMinor;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookEventData webhookEventData = (WebhookEventData) o;
    return Objects.equals(this.letterId, webhookEventData.letterId) &&
        Objects.equals(this.recipientId, webhookEventData.recipientId) &&
        Objects.equals(this.status, webhookEventData.status) &&
        Objects.equals(this.shipmentNumber, webhookEventData.shipmentNumber) &&
        Objects.equals(this.trackingNumber, webhookEventData.trackingNumber) &&
        Objects.equals(this.error, webhookEventData.error) &&
        Objects.equals(this.amountMinor, webhookEventData.amountMinor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(letterId, recipientId, status, shipmentNumber, trackingNumber, error, amountMinor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookEventData {\n");
    sb.append("    letterId: ").append(toIndentedString(letterId)).append("\n");
    sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    shipmentNumber: ").append(toIndentedString(shipmentNumber)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    amountMinor: ").append(toIndentedString(amountMinor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("letter_id");
    openapiFields.add("recipient_id");
    openapiFields.add("status");
    openapiFields.add("shipment_number");
    openapiFields.add("tracking_number");
    openapiFields.add("error");
    openapiFields.add("amount_minor");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("letter_id");
    openapiRequiredFields.add("status");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebhookEventData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebhookEventData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebhookEventData is not found in the empty JSON string", WebhookEventData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebhookEventData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WebhookEventData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WebhookEventData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("letter_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `letter_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("letter_id").toString()));
      }
      if ((jsonObj.get("recipient_id") != null && !jsonObj.get("recipient_id").isJsonNull()) && !jsonObj.get("recipient_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `recipient_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recipient_id").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("shipment_number") != null && !jsonObj.get("shipment_number").isJsonNull()) && !jsonObj.get("shipment_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipment_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipment_number").toString()));
      }
      if ((jsonObj.get("tracking_number") != null && !jsonObj.get("tracking_number").isJsonNull()) && !jsonObj.get("tracking_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tracking_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tracking_number").toString()));
      }
      if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebhookEventData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebhookEventData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebhookEventData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebhookEventData.class));

       return (TypeAdapter<T>) new TypeAdapter<WebhookEventData>() {
           @Override
           public void write(JsonWriter out, WebhookEventData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebhookEventData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebhookEventData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebhookEventData
   * @throws IOException if the JSON string is invalid with respect to WebhookEventData
   */
  public static WebhookEventData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebhookEventData.class);
  }

  /**
   * Convert an instance of WebhookEventData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

