/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import ru.doslano.sdk.ApiException;
import org.openapitools.client.model.WebhookEvent;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Колбек на финальный статус
     *
     * Если при отправке письма указан &#x60;callback_url&#x60;, мы шлём на него POST при достижении финального статуса — по каждому получателю (&#x60;recipient.sent&#x60; / &#x60;recipient.failed&#x60;) и агрегатно по письму (&#x60;letter.sent&#x60; / &#x60;letter.partial_failure&#x60; / &#x60;letter.failed&#x60; / &#x60;letter.cancelled&#x60;).  Отдельный случай &#x60;letter.cancelled&#x60; — когда адрес/ФИО не прошли проверку Почты России **уже после** ответа &#x60;201&#x60; (поздний preflight: проверка не успела завершиться в окне синхронного ответа). Письмо отменяется автоматически, в &#x60;data.error&#x60; — перечень полей с ошибками; исправьте данные и создайте письмо заново. Если же ошибка адреса выявлена **сразу** при создании — вы получаете её синхронно (HTTP 422 &#x60;address_validation_failed&#x60;), и колбек по такому письму НЕ шлётся. То есть на одно письмо приходит ровно один сигнал об адресной ошибке: либо синхронный 422, либо асинхронный &#x60;letter.cancelled&#x60;.  **Подпись.** Заголовок &#x60;X-Doslano-Signature: t&#x3D;&lt;unix&gt;,v1&#x3D;&lt;hex&gt;&#x60; — где &#x60;v1 &#x3D; HMAC_SHA256(secret, \&quot;&lt;t&gt;.\&quot; + raw_body)&#x60;, &#x60;secret&#x60; — секрет аккаунта из ЛК (раздел «API»). Проверьте подпись и свежесть &#x60;t&#x60; (±5 мин).  **Доставка.** At-least-once: ждём ответ &#x60;2xx&#x60;; иначе ретраим по нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем как недоставленный (видно в ЛК, можно переотправить). Дедуп — по &#x60;id&#x60; события. Порядок не гарантируется — сверяйтесь со &#x60;status&#x60; в теле. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void onLetterStatusChangedTest() throws ApiException {
        WebhookEvent webhookEvent = null;
        api.onLetterStatusChanged(webhookEvent);
        // TODO: test validations
    }

}
