/*
 * Doslano Integration API
 * Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import ru.doslano.sdk.ApiException;
import org.openapitools.client.model.CreateLetterRequest;
import org.openapitools.client.model.DryRunResult;
import java.io.File;
import org.openapitools.client.model.Letter;
import org.openapitools.client.model.LetterStatus;
import org.openapitools.client.model.ListLetters200Response;
import java.time.OffsetDateTime;
import org.openapitools.client.model.Problem;
import org.openapitools.client.model.TrackingInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LettersApi
 */
@Disabled
public class LettersApiTest {

    private final LettersApi api = new LettersApi();

    /**
     * Отправить письмо
     *
     * Создаёт и (по умолчанию) сразу оплачивает с баланса одно заказное письмо одним запросом. Опись формируется автоматически на нашей стороне.  Требуется scope &#x60;letters:write&#x60;. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createLetterTest() throws ApiException {
        CreateLetterRequest createLetterRequest = null;
        String idempotencyKey = null;
        DryRunResult response = api.createLetter(createLetterRequest, idempotencyKey);
        // TODO: test validations
    }

    /**
     * PDF описи вложения получателя
     *
     * Скачать PDF описи вложения (форма 107, версия отправителя) по отправлению конкретному получателю. Доступен после передачи в Почту (получатель в статусе &#x60;sent&#x60;/&#x60;delivered&#x60;); иначе &#x60;404&#x60;. Требуется scope &#x60;letters:read&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadRecipientInventoryPdfTest() throws ApiException {
        String id = null;
        String recipientId = null;
        File response = api.downloadRecipientInventoryPdf(id, recipientId);
        // TODO: test validations
    }

    /**
     * PDF фискального чека получателя
     *
     * Скачать PDF фискального чека (54-ФЗ) по отправлению конкретному получателю. Доступен, когда чек пробит и его PDF сохранён у нас (получатель в статусе &#x60;sent&#x60;/&#x60;delivered&#x60;); иначе &#x60;404&#x60;. Требуется scope &#x60;letters:read&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadRecipientReceiptPdfTest() throws ApiException {
        String id = null;
        String recipientId = null;
        File response = api.downloadRecipientReceiptPdf(id, recipientId);
        // TODO: test validations
    }

    /**
     * Статус письма
     *
     * Полное состояние письма с разбивкой по получателям и трек-номерами. Требуется scope &#x60;letters:read&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLetterTest() throws ApiException {
        String id = null;
        Letter response = api.getLetter(id);
        // TODO: test validations
    }

    /**
     * Трек-события получателя
     *
     * События трекинга Почты России по конкретному получателю (если трек-номер присвоен). Требуется scope &#x60;letters:read&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRecipientTrackingTest() throws ApiException {
        String id = null;
        String recipientId = null;
        TrackingInfo response = api.getRecipientTracking(id, recipientId);
        // TODO: test validations
    }

    /**
     * Список писем
     *
     * Письма аккаунта (все каналы — и API, и личный кабинет; канал указан в поле &#x60;channel&#x60;). Требуется scope &#x60;letters:read&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listLettersTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        LetterStatus status = null;
        OffsetDateTime createdFrom = null;
        OffsetDateTime createdTo = null;
        ListLetters200Response response = api.listLetters(limit, offset, status, createdFrom, createdTo);
        // TODO: test validations
    }

}
